### including warnings: i3status-rust-git ###
theme = "solarized-dark"
icons = "awesome"


[[block]]
block = "time"
interval = 30
format = "%Y-%m-%d %H:%M"

[[block]]
block = "custom"
command = "status_home.bash"
interval = 5

[[block]]
block = "custom"
interval = 360
command = "echo -n ' ' ; hostname -i | awk '{print $1}'"
on_click = "terminator -x bwm-ng"

[[block]]
block = "xrandr"
interval = 2
icons = true
resolution = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
clickable = false
interval = 1

[[block]]
block = "memory"
display_type = "swap"
format_swap = "{SUp}%"
clickable = false
warning_swap = 2
critical_swap = 25
interval = 30

[[block]]
block = "cpu"
interval = 1
#info = 60
#warning = 80
#critical = 90

[[block]]
block = "custom"
command = "status_cpu.bash"
interval = 1
on_click = "status.sh"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"


